[2023-07-14 21:40:10,836] INFO _log() L224  127.0.0.1 - - [14/Jul/2023 21:40:10] "POST /produto HTTP/1.1" 200 - - call_trace=c:\users\pedro\desktop\mvp pedro\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-07-14 21:40:28,126] WARNING cadastrar_operacao() L49   Erro ao adicionar a Ação 'KLBN3', Ação com o mesmo nome já está salvo dentro da base. O dado que você inseriu foi esse mesmo? - call_trace=C:\Users\pedro\Desktop\MVP Pedro\Projeto - Pedro Carvalho\ledger-acoes\meu_app_api\app.py L49  
[2023-07-14 21:40:28,130] INFO _log() L224  127.0.0.1 - - [14/Jul/2023 21:40:28] "[31m[1mPOST /produto HTTP/1.1[0m" 409 - - call_trace=c:\users\pedro\desktop\mvp pedro\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-07-14 21:41:00,400] INFO _log() L224  127.0.0.1 - - [14/Jul/2023 21:41:00] "GET /produto?id=1 HTTP/1.1" 200 - - call_trace=c:\users\pedro\desktop\mvp pedro\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-07-14 21:41:04,994] INFO _log() L224  127.0.0.1 - - [14/Jul/2023 21:41:04] "GET /produto?id=2 HTTP/1.1" 200 - - call_trace=c:\users\pedro\desktop\mvp pedro\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-07-14 21:41:23,732] WARNING del_operacao() L131  Erro ao deletar a ação #'3.', Ação não encontrada dentro da base de dados. É esse o nome mesmo da ação? - call_trace=C:\Users\pedro\Desktop\MVP Pedro\Projeto - Pedro Carvalho\ledger-acoes\meu_app_api\app.py L131 
[2023-07-14 21:41:23,740] INFO _log() L224  127.0.0.1 - - [14/Jul/2023 21:41:23] "[33mDELETE /produto?ticker_acao=3 HTTP/1.1[0m" 404 - - call_trace=c:\users\pedro\desktop\mvp pedro\env\lib\site-packages\werkzeug\_internal.py L224 
[2023-07-14 21:41:39,517] INFO _log() L224  127.0.0.1 - - [14/Jul/2023 21:41:39] "DELETE /produto?ticker_acao=KLBN3 HTTP/1.1" 200 - - call_trace=c:\users\pedro\desktop\mvp pedro\env\lib\site-packages\werkzeug\_internal.py L224 
